// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solace.DB;

#nullable disable

namespace Solace.DB.Migrations
{
    [DbContext(typeof(EarthDbContext))]
    partial class EarthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Solace.DB.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("BLOB");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.EncounterBuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EncounterBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.SharedBuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("BuildplateLastModifed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastViewed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Night")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfTimesViewed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SharedBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.TemplateBuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Night")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TemplateBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.Tile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectStoreId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ActivityLogEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BoostsEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Boosts");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BuildplateEF", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Night")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerDataObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PlayerBuildplates");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.HotbarEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hotbars");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.InventoryEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("NonStackableItemsData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackableItemsData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.JournalEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ProfileEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.RedeemedTappablesEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RedeemedTappables");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.TokensEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tokens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.CraftingSlotsEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CraftingSlots");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.SmeltingSlotsEF", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SmeltingSlots");
                });

            modelBuilder.Entity("Solace.DB.Models.Global.SharedBuildplateEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithMany("SharedBuildplates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Solace.DB.Models.Global.SharedBuildplateEF+HotbarItem", "Hotbar", b1 =>
                        {
                            b1.Property<Guid>("SharedBuildplateEFId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Count");

                            b1.Property<string>("InstanceId");

                            b1.Property<string>("Uuid")
                                .IsRequired();

                            b1.Property<int>("Wear");

                            b1.HasKey("SharedBuildplateEFId", "__synthesizedOrdinal");

                            b1.ToTable("SharedBuildplates");

                            b1
                                .ToJson("Hotbar")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SharedBuildplateEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Hotbar");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ActivityLogEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("ActivityLog")
                        .HasForeignKey("Solace.DB.Models.Player.ActivityLogEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BoostsEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Boosts")
                        .HasForeignKey("Solace.DB.Models.Player.BoostsEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Solace.DB.Models.Player.BoostsEF+ActiveBoost", "ActiveBoosts", b1 =>
                        {
                            b1.Property<Guid>("BoostsEFId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<long>("Duration");

                            b1.Property<string>("InstanceId")
                                .IsRequired();

                            b1.Property<string>("ItemId")
                                .IsRequired();

                            b1.Property<long>("StartTime");

                            b1.HasKey("BoostsEFId", "__synthesizedOrdinal");

                            b1.ToTable("Boosts");

                            b1
                                .ToJson("ActiveBoosts")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("BoostsEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("ActiveBoosts");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.BuildplateEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithMany("Buildplates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.HotbarEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Hotbar")
                        .HasForeignKey("Solace.DB.Models.Player.HotbarEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Solace.DB.Models.Player.HotbarEF+Item", "Items", b1 =>
                        {
                            b1.Property<Guid>("HotbarEFId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Count");

                            b1.Property<string>("InstanceId");

                            b1.Property<string>("Uuid")
                                .IsRequired();

                            b1.HasKey("HotbarEFId", "__synthesizedOrdinal");

                            b1.ToTable("Hotbars");

                            b1
                                .ToJson("Items")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("HotbarEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.InventoryEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Inventory")
                        .HasForeignKey("Solace.DB.Models.Player.InventoryEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.JournalEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Journal")
                        .HasForeignKey("Solace.DB.Models.Player.JournalEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.ProfileEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("Solace.DB.Models.Player.ProfileEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Solace.DB.Models.Player.Rubies", "Rubies", b1 =>
                        {
                            b1.Property<Guid>("ProfileEFId");

                            b1.Property<int>("Earned");

                            b1.Property<int>("Purchased");

                            b1.HasKey("ProfileEFId");

                            b1.ToTable("Profiles");

                            b1
                                .ToJson("Rubies")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ProfileEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Rubies")
                        .IsRequired();
                });

            modelBuilder.Entity("Solace.DB.Models.Player.RedeemedTappablesEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("RedeemedTappables")
                        .HasForeignKey("Solace.DB.Models.Player.RedeemedTappablesEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("System.Collections.Generic.Dictionary<string, long>", "Tappables", b1 =>
                        {
                            b1.Property<Guid>("RedeemedTappablesEFId");

                            b1.HasKey("RedeemedTappablesEFId");

                            b1.ToTable("RedeemedTappables");

                            b1
                                .ToJson("Tappables")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("RedeemedTappablesEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Tappables");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.TokensEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("Tokens")
                        .HasForeignKey("Solace.DB.Models.Player.TokensEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.CraftingSlotsEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("CraftingSlots")
                        .HasForeignKey("Solace.DB.Models.Player.Workshop.CraftingSlotsEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Solace.DB.Models.Player.Workshop.CraftingSlotEF", "Slots", b1 =>
                        {
                            b1.Property<Guid>("CraftingSlotsEFId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Locked");

                            b1.HasKey("CraftingSlotsEFId", "__synthesizedOrdinal");

                            b1.ToTable("CraftingSlots");

                            b1
                                .ToJson("Slots")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CraftingSlotsEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Solace.DB.Models.Player.Workshop.SmeltingSlotsEF", b =>
                {
                    b.HasOne("Solace.DB.Models.Account", "Account")
                        .WithOne("SmeltingSlots")
                        .HasForeignKey("Solace.DB.Models.Player.Workshop.SmeltingSlotsEF", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Solace.DB.Models.Player.Workshop.SmeltingSlot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("SmeltingSlotsEFId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("Locked");

                            b1.HasKey("SmeltingSlotsEFId", "__synthesizedOrdinal");

                            b1.ToTable("SmeltingSlots");

                            b1
                                .ToJson("Slots")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SmeltingSlotsEFId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Solace.DB.Models.Account", b =>
                {
                    b.Navigation("ActivityLog");

                    b.Navigation("Boosts");

                    b.Navigation("Buildplates");

                    b.Navigation("CraftingSlots");

                    b.Navigation("Hotbar");

                    b.Navigation("Inventory");

                    b.Navigation("Journal");

                    b.Navigation("Profile");

                    b.Navigation("RedeemedTappables");

                    b.Navigation("SharedBuildplates");

                    b.Navigation("SmeltingSlots");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
